[build]
  command = "cd frontend && npm run build"
  publish = "frontend/.next"

[build.environment]
  # Public environment variables only (no secrets!)
  NEXT_PUBLIC_WAGA_COFFEE_TOKEN_ADDRESS = "0xE69bdd3E783212D11522E7f0057c9F52FC4D0A39"
  NEXT_PUBLIC_WAGA_PROOF_OF_RESERVE_ADDRESS = "0xaA42A460107A61D34D461fb59c46343b1a8FAdc5"
  NEXT_PUBLIC_WAGA_INVENTORY_MANAGER_ADDRESS = "0xe882dcD6F1283F83Ab19F954d70fC024eE70A908"
  NEXT_PUBLIC_WAGA_REDEMPTION_CONTRACT_ADDRESS = "0xc235C005202a9ec26d59120B8e9c2cc6AB432fC4"
  NEXT_PUBLIC_CHAINLINK_FUNCTIONS_ROUTER = "0xf9B8fc078197181C841c296C876945aaa425B278"
  NEXT_PUBLIC_CHAINLINK_DON_ID = "fun-base-sepolia-1"
  NEXT_PUBLIC_CHAINLINK_SUBSCRIPTION_ID = "429"

# Add secrets like PINATA_JWT and WAGA_API_KEY through the Netlify dashboard!

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
